name: totem
description: Be known.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.34+73

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  after_layout: ^1.1.0
  agora_rtc_engine:
    git:
      url: https://github.com/totem-technologies/Agora-Flutter-SDK.git
      ref: 5_3_1_rev1
  audio_streamer: ^2.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  camera: ^0.10.0
  clipboard: ^0.1.3
  cloud_firestore: ^3.4.9
  cloud_functions: ^3.3.8
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.0
  datetime_picker_formfield: ^2.0.0
  decorated_icon: ^1.2.1
  diffutil_dart: ^3.0.0
  email_validator: ^2.0.1
  firebase_analytics: ^9.3.6
  firebase_app_check: ^0.0.7
  firebase_auth: ^3.0.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.4.4
  firebase_dynamic_links: ^4.0.8
  firebase_storage: ^10.0.1
  flutter_device_type: ^0.4.0
  flutter_foreground_task: ^3.5.4
  flutter_markdown: ^0.6.12
  flutter_reorderable_list: ^1.2.0
  flutter_riverpod: ^1.0.0
  flutter_sim_country_code: ^0.1.2
  flutter_spinbox: ^0.10.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  go_router: ^5.0.0
  image: ^3.1.0
  image_picker: ^0.8.5+3
  intl_phone_number_input: ^0.7.0+2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  js: ^0.6.4
  keybinder: ^1.0.0
  keyboard_actions: ^4.0.0
  libphonenumber_plugin: ^0.2.3
  logger: ^1.0.0-nullsafety.0
  lottie: ^1.4.3
  noise_meter: ^3.1.0
  package_info_plus: ^2.0.0
  path_provider: ^2.0.10
  permission_handler: ^10.0.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.2
  rxdart: ^0.27.2
  sentry_flutter: ^6.11.1
  share_plus: ^5.0.0
  shared_preferences: ^2.0.12
  slide_to_act: ^2.0.1
  state_notifier: ^0.7.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.2
  uuid: ^3.0.6
  wakelock: ^0.6.1+2
  web_browser_detect: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/android_download.png
    - assets/background_shape.svg
    - assets/face.svg
    - assets/home_logo.svg
    - assets/ios_download.png
    - assets/onboarding_finish_flag.png
    - assets/onboarding_help_book.png
    - assets/onboarding_pass_baton.png
    - assets/onboarding_play_button.png
    - assets/onboarding_talking_person.png
    - assets/onboarding_totem_icon.png
    - assets/view_circle.svg
    - assets/animations/totem_reveal.json
    - assets/totem_icon.svg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Recoleta
      fonts:
        - asset: fonts/Recoleta-Medium.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
