name: totem
description: Be known.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.0+32

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  after_layout: ^1.1.0
  agora_rtc_engine: ^5.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  camera: ^0.9.4+5
  cloud_firestore: ^3.1.0
  cloud_functions: ^3.1.1
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  diffutil_dart: ^3.0.0
  email_validator: ^2.0.1
  firebase_app_check: ^0.0.6+4
  firebase_auth: ^3.0.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.4.4
  firebase_storage: ^10.0.1
  firebase_dynamic_links: ^4.0.8
  flutter_device_type: ^0.4.0
  flutter_foreground_task: ^3.5.4
  flutter_reorderable_list: ^1.2.0
  flutter_riverpod: ^1.0.0
  flutter_sim_country_code: ^0.1.2
  flutter_spinbox: ^0.9.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.0
  hexcolor: ^2.0.4
  image: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  intl: ^0.17.0
  keybinder: ^1.0.0
  keyboard_actions: ^3.4.4
  libphonenumber_plugin: ^0.2.3
  logger: ^1.0.0-nullsafety.0
  package_info_plus: ^1.3.0
  permission_handler: ^9.2.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.2
  rxdart: ^0.27.2
  shared_preferences: ^2.0.12
  slide_to_act: ^2.0.1
  state_notifier: ^0.7.0
  simple_shadow: ^0.3.0
  cupertino_will_pop_scope: ^1.2.0
  url_launcher: ^6.0.2
  universal_html: ^2.0.8
  web_browser_detect: ^2.0.2
  collection: ^1.16.0
  uuid: ^3.0.6
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

dependency_overrides:
  provider: ^6.0.2

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/alert.svg
    - assets/android_download.png
    - assets/arrow_next.svg
    - assets/background_shape.svg
    - assets/cam.svg
    - assets/check.svg
    - assets/close.svg
    - assets/face.svg
    - assets/fast_forward.svg
    - assets/info.svg
    - assets/ios_download.png
    - assets/leave.svg
    - assets/microphone.svg
    - assets/microphone_mute.svg
    - assets/microphone_force.svg
    - assets/less.svg
    - assets/more.svg
    - assets/more_info.svg
    - assets/profile.svg
    - assets/send.svg
    - assets/sort.svg
    - assets/unlock.svg
    - assets/view_circle.svg
    - assets/circle_check.svg
    - assets/active_sharing.svg
    - assets/video.svg
    - assets/video_stop.svg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Recoleta
      fonts:
        - asset: fonts/Recoleta-Medium.ttf
          weight: 600
