name: totem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+9

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.0
  cloud_firestore: ^3.1.0
  cloud_functions: ^3.1.1
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.0
  firebase_crashlytics: ^2.4.4
  intl_phone_number_input: ^0.7.0+2
  flutter_spinkit: ^5.0.0
  flutter_riverpod: ^1.0.0
  state_notifier: ^0.7.0
  logger: ^1.0.0-nullsafety.0
  hexcolor: ^2.0.4
  pin_code_fields: ^7.3.0
  flutter_svg: ^0.23.0
  rxdart: ^0.27.2
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_spinbox: ^0.6.0
  datetime_picker_formfield: ^2.0.0
  keyboard_actions: ^3.4.4
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.1.0
  agora_rtc_engine: ^4.0.7
  after_layout: ^1.1.0
  permission_handler: ^8.3.0
  image_picker: ^0.8.4+4
  camera:
    git:
      url: https://github.com/Phase2Industries/plugins.git
      path: packages/camera/camera
  image_crop: ^0.4.0
  flutter_reorderable_list:
    git:
      url: https://github.com/Phase2Industries/flutter_reorderable_list.git
  flutter_slidable: ^0.6.0
  diffutil_dart: ^3.0.0
  package_info_plus: ^1.3.0
  libphonenumber_plugin:
  image: ^3.1.0
  email_validator: ^2.0.1
  flutter_foreground_task: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/alert.svg
    - assets/arrow_next.svg
    - assets/background_shape.svg
    - assets/background_shape_2.svg
    - assets/check.svg
    - assets/close.svg
    - assets/fast_forward.svg
    - assets/home_background.svg
    - assets/info.svg
    - assets/leave.svg
    - assets/microphone.svg
    - assets/microphone_mute.svg
    - assets/microphone_force.svg
    - assets/less.svg
    - assets/more.svg
    - assets/more_info.svg
    - assets/profile.svg
    - assets/send.svg
    - assets/sort.svg
    - assets/unlock.svg
    - assets/view_circle.svg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Recoleta
      fonts:
        - asset: fonts/Recoleta-Regular.ttf
