name: Build
on: [workflow_dispatch]

jobs:
  build_ios:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v2
    # Install flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.x'
        cache: true
    - run: fastlane ios internal
      env:
        MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

