name: Flutter Test
on: [push]
jobs:
  flutter-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.x'
          cache: true
      - run: flutter analyze
      - run: flutter test
  server-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./server/functions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: server/functions/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run build